[package]
name = "sourcetrait_crossplat_windows"
version = "0.0.1"
edition = "2024"
description = "Windows driver for SourceTrait CrossPlat"
authors = ["SourceTrait <development@sourcetrait.com"]
license = "AGPL-3.0-or-later WITH GPL-3.0-linking-source-exception"
repository = "https://github.com/sourcetrait/sourcetrait_common_unix"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "common", "cross", "windows"]

[dependencies]
snafu.workspace = true
sourcetrait_twostr.workspace = true
sourcetrait_crossplat_bridge = { workspace = true, optional = true }
strum.workspace = true
widestring.workspace = true
windows-sys.workspace = true

[dev-dependencies]
sourcetrait_testing.workspace = true

[features]
default = ["crossplat"]
crossplat = ["sourcetrait_crossplat_bridge"]
